<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! - Open Source Content Management" -->
<feed xmlns="http://www.w3.org/2005/Atom"  xml:lang="es-es">
	<title type="text">FLISoL Fusagasugá - Inicio</title>
	<subtitle type="text">Festival Latinoamericano de Instalación de Software Libre - Nodo Fusagasugá</subtitle>
	<link rel="alternate" type="text/html" href="http://fusa.flisol.info"/>
	<id>http://fusa.flisol.info/2015/index.php</id>
	<updated>2018-12-19T00:40:40+00:00</updated>
	<generator uri="http://joomla.org" version="2.5">Joomla! - Open Source Content Management</generator>
	<link rel="self" type="application/atom+xml" href="http://fusa.flisol.info/2015/index.php?format=feed&amp;type=atom"/>
	<entry>
		<title>¿Cuándo y dónde?</title>
		<link rel="alternate" type="text/html" href="http://fusa.flisol.info/2015/index.php/participar/cuando-y-donde"/>
		<published>2014-03-14T03:17:07+00:00</published>
		<updated>2014-03-14T03:17:07+00:00</updated>
		<id>http://fusa.flisol.info/2015/index.php/participar/cuando-y-donde</id>
		<author>
			<name>Deiby Od</name>
			<email>deibyod&commat; gmail . com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h3 id=&quot;Fusagasug.2BAOE.2C_Cundinamarca&quot;&gt;Fusagasugá, Cundinamarca&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Lugar:&lt;/strong&gt; Institución Educativa Municipal Teodoro Aya Villaveces. Carrera 7 con Calle 16. &lt;span id=&quot;line-14&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-15&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Fecha:&lt;/strong&gt; Sábado 11 de Abril del 2015. &lt;span id=&quot;line-16&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-17&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Hora:&lt;/strong&gt; 09:00 am a 04:00 pm. &lt;span id=&quot;line-18&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-19&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Hashtag (Twitter/Facebook):&lt;/strong&gt; &lt;a class=&quot;https&quot; href=&quot;https://twitter.com/search?q=%23FlisolFusa&quot;&gt;#FlisolFusa&lt;/a&gt; &lt;span id=&quot;line-20&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-21&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Fan page en Facebook:&lt;/strong&gt; &lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/flisolfusa&quot;&gt;https://www.facebook.com/flisolfusa&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h3 id=&quot;Fusagasug.2BAOE.2C_Cundinamarca&quot;&gt;Fusagasugá, Cundinamarca&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Lugar:&lt;/strong&gt; Institución Educativa Municipal Teodoro Aya Villaveces. Carrera 7 con Calle 16. &lt;span id=&quot;line-14&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-15&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Fecha:&lt;/strong&gt; Sábado 11 de Abril del 2015. &lt;span id=&quot;line-16&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-17&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Hora:&lt;/strong&gt; 09:00 am a 04:00 pm. &lt;span id=&quot;line-18&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-19&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Hashtag (Twitter/Facebook):&lt;/strong&gt; &lt;a class=&quot;https&quot; href=&quot;https://twitter.com/search?q=%23FlisolFusa&quot;&gt;#FlisolFusa&lt;/a&gt; &lt;span id=&quot;line-20&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-21&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Fan page en Facebook:&lt;/strong&gt; &lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/flisolfusa&quot;&gt;https://www.facebook.com/flisolfusa&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;</content>
		<category term="Destacado" />
		<category term="Uncategorised" />
	</entry>
	<entry>
		<title>¿Qué es?</title>
		<link rel="alternate" type="text/html" href="http://fusa.flisol.info/2015/index.php/info/que-es"/>
		<published>2014-03-14T03:17:49+00:00</published>
		<updated>2014-03-14T03:17:49+00:00</updated>
		<id>http://fusa.flisol.info/2015/index.php/info/que-es</id>
		<author>
			<name>Deiby Od</name>
			<email>deibyod&commat; gmail . com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h2 id=&quot;Presentaci.2BAPM-n&quot;&gt;Presentación&lt;/h2&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;Este año se realiza &lt;strong&gt;por tercera vez en Fusagasugá&lt;/strong&gt; uno de los &lt;strong&gt;eventos tecnológicos más importantes de Latinoamerica&lt;/strong&gt; y ahora del mundo: &lt;strong&gt;el FLISoL&lt;/strong&gt;. &lt;span id=&quot;line-34&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;Continuaremos construyendo una ciudad con &lt;strong&gt;oportunidades&lt;/strong&gt; para acceder al &lt;strong&gt;conocimiento&lt;/strong&gt;, a la &lt;strong&gt;tecnología&lt;/strong&gt;, conservando al máximo tu &lt;strong&gt;derecho a la libertad y la privacidad&lt;/strong&gt;. &lt;span id=&quot;line-35&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-36&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;img src=&quot;http://flisol.info/moin_static194/sol/img/icon-info.png&quot; border=&quot;0&quot; alt=&quot;{i}&quot; title=&quot;{i}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; También te invitamos a conocer la información del &lt;a href=&quot;http://flisol.info/FLISOL2015&quot;&gt;FLISoL Internacional&lt;/a&gt;. &lt;span id=&quot;line-37&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-38&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;em&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/star_on.png&quot; border=&quot;0&quot; alt=&quot;{*}&quot; title=&quot;{*}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Fusagasugá libre.&lt;/strong&gt;&lt;/em&gt; &lt;span id=&quot;line-39&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-40&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;hr class=&quot;hr6&quot; /&gt;
&lt;p class=&quot;line874&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h2 id=&quot;A.2BAL8-Qu.2BAOk_es_el_FLISoL.3F&quot;&gt;¿Qué es el FLISoL?&lt;/h2&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;El &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2015/&quot;&gt;Festival Latinoamericano de Instalación de Software Libre (FLISoL)&lt;/a&gt; es el evento de difusión de &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/DescubreElSoftwareLibre&quot;&gt;Software Libre&lt;/a&gt; &lt;strong&gt;más grande en Latinoamerica&lt;/strong&gt;. Se realiza &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2005/&quot;&gt;desde el año 2005&lt;/a&gt;. &lt;span id=&quot;line-45&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-46&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;Su principal objetivo es &lt;strong&gt;promover el uso del software libre&lt;/strong&gt;, dando a conocer al público en general su &lt;strong&gt;filosofía, alcances, avances y desarrollo&lt;/strong&gt;. &lt;span id=&quot;line-47&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-48&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;A tal fin, las diversas comunidades locales de software libre &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2015/Ciudades&quot;&gt;(en cada país/ciudad/localidad)&lt;/a&gt;, organizan simultáneamente eventos en los que se instala, de manera gratuita y totalmente legal, software libre en las computadoras que llevan los asistentes, se ofrecen charlas, ponencias y talleres, sobre temáticas locales, nacionales y latinoamericanas en torno al Software Libre, &lt;strong&gt;en toda su gama de expresiones: artística, académica, empresarial y social&lt;/strong&gt;.&lt;/p&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h2 id=&quot;Presentaci.2BAPM-n&quot;&gt;Presentación&lt;/h2&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;Este año se realiza &lt;strong&gt;por tercera vez en Fusagasugá&lt;/strong&gt; uno de los &lt;strong&gt;eventos tecnológicos más importantes de Latinoamerica&lt;/strong&gt; y ahora del mundo: &lt;strong&gt;el FLISoL&lt;/strong&gt;. &lt;span id=&quot;line-34&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;Continuaremos construyendo una ciudad con &lt;strong&gt;oportunidades&lt;/strong&gt; para acceder al &lt;strong&gt;conocimiento&lt;/strong&gt;, a la &lt;strong&gt;tecnología&lt;/strong&gt;, conservando al máximo tu &lt;strong&gt;derecho a la libertad y la privacidad&lt;/strong&gt;. &lt;span id=&quot;line-35&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-36&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;img src=&quot;http://flisol.info/moin_static194/sol/img/icon-info.png&quot; border=&quot;0&quot; alt=&quot;{i}&quot; title=&quot;{i}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; También te invitamos a conocer la información del &lt;a href=&quot;http://flisol.info/FLISOL2015&quot;&gt;FLISoL Internacional&lt;/a&gt;. &lt;span id=&quot;line-37&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-38&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt;&lt;em&gt;&lt;strong&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/star_on.png&quot; border=&quot;0&quot; alt=&quot;{*}&quot; title=&quot;{*}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Fusagasugá libre.&lt;/strong&gt;&lt;/em&gt; &lt;span id=&quot;line-39&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-40&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;hr class=&quot;hr6&quot; /&gt;
&lt;p class=&quot;line874&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h2 id=&quot;A.2BAL8-Qu.2BAOk_es_el_FLISoL.3F&quot;&gt;¿Qué es el FLISoL?&lt;/h2&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;El &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2015/&quot;&gt;Festival Latinoamericano de Instalación de Software Libre (FLISoL)&lt;/a&gt; es el evento de difusión de &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/DescubreElSoftwareLibre&quot;&gt;Software Libre&lt;/a&gt; &lt;strong&gt;más grande en Latinoamerica&lt;/strong&gt;. Se realiza &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2005/&quot;&gt;desde el año 2005&lt;/a&gt;. &lt;span id=&quot;line-45&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-46&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;Su principal objetivo es &lt;strong&gt;promover el uso del software libre&lt;/strong&gt;, dando a conocer al público en general su &lt;strong&gt;filosofía, alcances, avances y desarrollo&lt;/strong&gt;. &lt;span id=&quot;line-47&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-48&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;A tal fin, las diversas comunidades locales de software libre &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2015/Ciudades&quot;&gt;(en cada país/ciudad/localidad)&lt;/a&gt;, organizan simultáneamente eventos en los que se instala, de manera gratuita y totalmente legal, software libre en las computadoras que llevan los asistentes, se ofrecen charlas, ponencias y talleres, sobre temáticas locales, nacionales y latinoamericanas en torno al Software Libre, &lt;strong&gt;en toda su gama de expresiones: artística, académica, empresarial y social&lt;/strong&gt;.&lt;/p&gt;&lt;/div&gt;</content>
		<category term="Destacado" />
		<category term="Uncategorised" />
	</entry>
	<entry>
		<title>¿Qué habrá?</title>
		<link rel="alternate" type="text/html" href="http://fusa.flisol.info/2015/index.php/cronograma/que-habra"/>
		<published>2014-03-14T03:18:27+00:00</published>
		<updated>2014-03-14T03:18:27+00:00</updated>
		<id>http://fusa.flisol.info/2015/index.php/cronograma/que-habra</id>
		<author>
			<name>Deiby Od</name>
			<email>deibyod&commat; gmail . com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h2 id=&quot;Actividades&quot;&gt;Actividades&lt;/h2&gt;
&lt;h3 id=&quot;Plazoleta_Stallman&quot;&gt;Plazoleta Stallman&lt;/h3&gt;
&lt;p&gt;&lt;span id=&quot;line-56&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;HORA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;TÍTULO DE PONENCIA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;DESCRIPCIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;PONENTE(S)&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-57&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;9:00 am - 10:00 am&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Cultura Libre en Fusagasugá&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Apertura del FLISoL&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Comité Organizador&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.fusa.flisol.info&quot;&gt;FLISoL Fusagasugá&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-58&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;10:00 am - 11:00 am&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Apropiación Social de la Tecnología: alternativa para crear NUESTRAS PROPIAS SOLUCIONES&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;La #BVS -Buena Vibra Siempre- es una oleada de personas que vienen contagiando a sus comunidades, una forma más de ser parte de la solución sin mucho &quot;enredo&quot;. Nos apasiona compartir lo que aprendemos haciéndolo ver &quot;facilito&quot; con el fin de CREAR JUNTOS soluciones, a nuestras problemáticas cotidianas. En esta ocasión compartiremos algo del cómo usar fácilmente la tecnología para crear soluciones de accesibilidad a personas con algún tipo de discapacidad y también como crear redes wifi con materiales de bajo costo. Te llamaría la atención dejarte contagiar de la #BVS ?? Estas muy pero muy invitado.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Wilson Daniel Gordillo Ochoa (Girardot(Cund)/Espinal(Tolima))&lt;/strong&gt;. &lt;br /&gt; Ingeniero de Sistemas de profesión. Docente Investigador por pasión e Innovador Social por convicción.&lt;br /&gt; Ingeniero de Sistemas. Especialista en Docencia Universitaria y en Redes de Telecomunicaciones. Magíster en Educación.&lt;br /&gt; Actualmente Docente Investigador de la Universidad de Cundinamarca Fusagasugá. Programa Ingeniería de Sistemas.&lt;br /&gt; Docente Catedrático de la Universidad Piloto de Colombia, seccional Girardot.&lt;br /&gt; Gestor de Proyectos de Investigación y Laboratorios de Innovación Social como Red Fusa Libre, Red Espinal Libre, enREDate, cuyo propósito en común es apropiar socialmente el conocimiento en nuestras comunidades convirtiendolas activamente en parte de la solución para mejorar sus condiciones de vida.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.redfusalibre.co&quot;&gt;Red Fusa Libre&lt;/a&gt;&lt;br /&gt; Red Espinal Libre&lt;br /&gt; EnREDate&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-59&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;11:00 am - 12:00 m&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Flujo de Trabajo Orientado a Código con Drupal&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Esta charla quiere compartir la experiencia de la fábrica de software de la ACDTIC, en la construcción de sitios y portales web distritales, a partir de la estandarización, modularización, y contribución de características funcionales para el CMS Drupal, las cuales son desarrolladas en un ambiente de desarrollo colaborativo. &lt;br /&gt; Nuestro enfoque apropia Software Libre, mejores prácticas de desarrollo, metodologías ágiles y las recomendaciones de la Guía de Sitios Web v3.0, para brindar accesibilidad, usabilidad y gobierno electrónico.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Fabián Hernández / David Triana (Bogotá)&lt;/strong&gt;&lt;br /&gt; &lt;strong&gt;Fabián Hernández. &lt;/strong&gt;Soy Ingeniero Electrónico bogotano, usuario y promotor de Software Libre con experiencia en el campo de desarrollo web y administración de sistemas GNU/Linux, miembro cofundador de la comunidad Juuntos Latinoamérica y desarrollador activo de la plataforma CMS Jokte!. Actualmente creando proyectos con Drupal para las Entidades del Distrito Capital.&lt;br /&gt; &lt;strong&gt;David Triana.&lt;/strong&gt; Ingeniero de sistemas entusiasta del software libre, desarrollador frontend con experiencia de 5 años utilizando CMS. Desarrollador de la alta consejería TIC, actualmente creando proyectos con Drupal para diferentes Entidades del Distrito Capital.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Fábrica de Software de la Alta Consejería Distrial de TIC&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-60&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;12:00 md - 12:45 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;ALMUERZO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-61&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;1:00 pm - 2:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Visión Artificial con Raspberry pi&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Metodologías de visión artificial sobre dispositivo embebido Raspberry pi&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Diego Alveniz Escobar Figueroa (Fusagasugá)&lt;/strong&gt;. Estudiante de Ing. Electrónica (UDEC), Promotor de Cultura Libre, apasionado por la visión artificial y el Hardware libre. Perteneciente al Colectivo Ingenio Popular y semillero de Investigación KINESTASIS UDEC.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Ingenio Popular&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-62&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;2:00 pm - 3:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Normatividad Distrital para el uso y apropiación de Software Libre&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;El objetivo de la charla es hacer un recuento de las diferentes aplicaciones de herramientas, plataformas, metodologías y proyectos que hacen uso de la política de software libre en el Distrito Capital.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Nelson Darío Rico Pinzón (Bogotá)&lt;/strong&gt;. Ingeniero de sistemas con 30 años de experiencia docente, se ha desempeñado como director de sistemas en entidades distritales y nacionales, actualmente trabaja como profesional especializado en la secretaría técnica de la Comisión Distrital de Sistemas CDS, director de proyectos especiales y responsable de la promoción del Software Libre en la Alta Consejería Distrital de Tecnologías de la Información y las Comunicaciones TIC.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Secretaría General. Alta Consejería Distrital de TIC&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-63&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;3:00 pm - 3:30 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Cierre del FLISOL&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Comité Organizador&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.fusa.flisol.info&quot;&gt;FLISoL Fusagasugá&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-64&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;3:30 pm - 4:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;REFRIGERIOS&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt;&lt;span id=&quot;line-65&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-66&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h3 id=&quot;Plazoleta_Torvalds&quot;&gt;Plazoleta Torvalds&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;HORA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;TÍTULO DE PONENCIA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;DESCRIPCIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;PONENTE(S)&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-68&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;10:00 am - 11:00 am&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Estudio de la criptografía&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Una descripción de la historia de la criptografía y el estudio actual de la misma. El objetivo principal de la criptografía en la antigüedad era conseguir la confidencialidad de los mensajes. En la actualidad es la única forma de proteger nuestra información en la era digital. Se demostraran los sistemas de criptoanalisis para saber que tan segura esta nuestra información.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Daniel Camilo Ramirez Martinez (Chía)&lt;/strong&gt;. Estudiante de X semestre de Ingeniería de Sistemas (UdeC). Tecnología en formulación y evaluación de proyectos. Director de desarrollo Educamos Online.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Independiente&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-69&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;11:00 am - 12:00 m&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;¿Que necesito para crear un videojuego?&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;En esta charla veremos el estado de la industria de los videojuegos en Colombia, como comenzar y que necesitamos para dar los primeros pasos en esta fascinante industria.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Cristian Camilo Velasquez (Bogotá/Fusagasugá)&lt;/strong&gt;. Soy scrum master en Brainz interactive, miembro activo de la comunidad agil colombiana.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.brainz.co&quot;&gt;Brainz interactive&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-70&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;12:00 md - 12:45 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;ALMUERZO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-71&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;1:00 pm - 2:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Realidad Aumentada&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Software libre&lt;br /&gt; IDE: Eclipse&lt;br /&gt; Librería AR: NyARToolKit 4.1&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Jaime Paez (Bogotá)&lt;/strong&gt;. Ing de Sistemas. Magister en Educación de la Universidad Pedagógica Nacional. Docente Investigador de la Universidad Cooperativa de Colombia. Líder del grupo de investigación NEOTIC y líder del semillero de Investigación MULTYSO.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Universidad Cooperativa de Colombia - Semillero de investigación Multyso&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-72&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;2:00 pm - 3:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Zentyal Development Edition, solución para la pequeña y mediana empresa&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;El Objetivo principal es realizar un taller teórico-practico donde se verán: Instalación y configuración, configuración de red, configuración dominio, configuración Grupo de trabajo, configuración políticas de seguridad, casos de uso y aplicación, ventajas del uso de Zentyal.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Jaime Daniel Quintero Avalo (Bogotá)&lt;/strong&gt;. Estudiante de Ingeniería de sistemas de la Universidad Cooperativa de Colombia. Actualmente Líder activo del semillero de investigación MULTYSO.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Universidad Cooperativa de Colombia - Semillero de investigación Multyso&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h3 id=&quot;Plazoleta_Baker&quot;&gt;Plazoleta Baker&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;HORA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;TÍTULO DE PONENCIA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;DESCRIPCIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;PONENTE(S)&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-76&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;10:00 am - 12:00 md&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Desarrollo de App Movil utilizando Firefox OS&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Se Aprenderá como desarrollar un app Movil con el nuevo sistema operativo Firefox OS, basado en HTML5 con núcleo Linux y de código abierto.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Giovanny Andres Cifuentes (Fusagasugá)&lt;/strong&gt;. Desarrollador freelance. Entusiasta de las metodologías ágiles, emprendimiento y software libre.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.mozillacolombia.org&quot;&gt;Mozilla Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-77&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;12:00 md - 12:45 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;ALMUERZO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-78&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;1:00 pm - 2:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Experiencias con agilismo&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;En esta charla se hará una pequeña introducción a las metodologías ágiles y como han sido aplicadas en los entornos donde nos desarrollamos con un pequeño taller práctico&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;&lt;a class=&quot;nonexistent&quot; href=&quot;http://flisol.info/LocXue&quot;&gt;LocXue&lt;/a&gt; (Fusagasugá)&lt;/strong&gt;. Somos un semillero de la Universidad de Cundinamarca pertenecientes a la comunidad agilista, enfocados en metodologias agiles para el desarrollo de nuestros proyectos, en los cuales nos gusta innovar y ayudar en nuestra comunidad esperando generar espacios donde el conocimiento se comparta.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/locxue&quot;&gt;Comunidad Agilista&lt;/a&gt;&lt;br /&gt; &lt;a class=&quot;http&quot; href=&quot;http://www.agilescolombia.org&quot;&gt;Agiles Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-79&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;2:00 pm - 3:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Webcomponents by Mozilla&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;¿Son los webcomponents realmente necesarios? Un vistazo a lo bueno, lo malo y inimaginable sobre el futuro de los webcomponents.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Giovanny Andres Gongora Granada (Ibague)&lt;/strong&gt;. Desarrollador con 8 años de experiencia personal. Miembro de Mozilla Hispano y Mozilla Colombia. Ayuda en Firefox Marketplace (marketplace.firefox.com), i18n y es entrenador de Firefox OS Colombia. Dicta charlas de Web Abierta y Open Source.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.mozillacolombia.org&quot;&gt;Mozilla Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;En años anteriores contamos con la fortuna de recibir el apoyo incondicional de &lt;strong&gt;grandes amigos&lt;/strong&gt; de la cultura libre: &lt;span id=&quot;line-76&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-77&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Gloria Meneces&lt;/strong&gt;, representante de Mozilla para Colombia, Mozillian y miembro de &lt;strong&gt;Mozilla Colombia&lt;/strong&gt; socializando con nosotros el mundo tras mozilla y patrocinando el evento. &lt;span id=&quot;line-78&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-79&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Edgar Daniel Cruz Zamudio&lt;/strong&gt;, realizador audiovisual del colectivo Cine Al Aire, participante, realizador y organizador de diferentes festivales, clips y talleres. &lt;span id=&quot;line-80&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-81&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Juan Sebastian Rojas&lt;/strong&gt;, Ingeniero de Sistemas de la Universidad de Cundinamarca, Certified Ethical Hacker, ponente de charlas de seguridad informática y Consultor Senior de seguridad en Entidad Bancaria. &lt;span id=&quot;line-82&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-83&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Jessica Selene&lt;/strong&gt; desde &lt;strong&gt;Argentina&lt;/strong&gt; compartiendo diversos proyectos vínculados a tecnologías libres, entre ellos las redes libres. &lt;a class=&quot;nonexistent&quot; href=&quot;http://flisol.info/blog.altermundi.net/article/se-hace-camino-al-andar/&quot;&gt;En este link puedes ver como contó su experiencia&lt;/a&gt;. &lt;span id=&quot;line-84&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-85&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;También &lt;strong&gt;Fabian Hernandez&lt;/strong&gt; del colectivo latinoamericano &lt;strong&gt;Juuntos&lt;/strong&gt;, haciendo difusión del proyecto de CMS libre y latinoamérico Jokte!. &lt;a class=&quot;https&quot; href=&quot;https://groups.google.com/forum/#%21topic/juuntos/eSrj3PoPAYo&quot;&gt;Aqui en este link nos comparte un poco de su experiencia&lt;/a&gt; &lt;span id=&quot;line-86&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-87&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompañaron e hicieron parte de la organización algun@s de los miembros de la comunidad hermana &lt;strong&gt;Red Espinal Libre&lt;/strong&gt; que junto a &lt;strong&gt;Red Fusa Libre&lt;/strong&gt; y Jessica permitieron importantes espacios en el evento. &lt;a class=&quot;http&quot; href=&quot;http://espinallibre.wordpress.com/2013/04/02/invitacion-flisol-fusa-20abril/&quot;&gt;En este link vemos como fue su invitación a participar&lt;/a&gt;. &lt;span id=&quot;line-88&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-89&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;L@s amig@s de &lt;strong&gt;Novenopiso TV/WEB&lt;/strong&gt; hicieron cobertura del evento en su capitulo número 12. &lt;a class=&quot;https&quot; href=&quot;https://www.youtube.com/watch?v=ff8luACoN5g&quot;&gt;Puedes ver el video en este link&lt;/a&gt;. (Con la salvedad de que Daivi era Deiby &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/smile4.png&quot; border=&quot;0&quot; alt=&quot;;)&quot; title=&quot;;)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; ). &lt;span id=&quot;line-90&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-91&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;Contamos con la participación de numerosos colectivos afines a esta iniciativa, visitantes y colaboradores, y en especial, entregados voluntarios y la acogida y apoyo de la misma comunidad. &lt;span id=&quot;line-92&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-93&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;&lt;img src=&quot;http://flisol.info/moin_static194/sol/img/icon-info.png&quot; border=&quot;0&quot; alt=&quot;{i}&quot; title=&quot;{i}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; &lt;em&gt;Puedes ver la información del FLISoL del año pasado &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2014/Colombia/Fusagasuga&quot;&gt;Aquí&lt;/a&gt;, del antepasado &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2013/Colombia/Fusagasuga&quot;&gt;Aquí&lt;/a&gt;&lt;/em&gt; y &lt;strong&gt;¡reunir energías para este que se viene!.&lt;/strong&gt;&lt;/p&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h2 id=&quot;Actividades&quot;&gt;Actividades&lt;/h2&gt;
&lt;h3 id=&quot;Plazoleta_Stallman&quot;&gt;Plazoleta Stallman&lt;/h3&gt;
&lt;p&gt;&lt;span id=&quot;line-56&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;HORA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;TÍTULO DE PONENCIA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;DESCRIPCIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;PONENTE(S)&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-57&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;9:00 am - 10:00 am&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Cultura Libre en Fusagasugá&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Apertura del FLISoL&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Comité Organizador&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.fusa.flisol.info&quot;&gt;FLISoL Fusagasugá&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-58&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;10:00 am - 11:00 am&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Apropiación Social de la Tecnología: alternativa para crear NUESTRAS PROPIAS SOLUCIONES&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;La #BVS -Buena Vibra Siempre- es una oleada de personas que vienen contagiando a sus comunidades, una forma más de ser parte de la solución sin mucho &quot;enredo&quot;. Nos apasiona compartir lo que aprendemos haciéndolo ver &quot;facilito&quot; con el fin de CREAR JUNTOS soluciones, a nuestras problemáticas cotidianas. En esta ocasión compartiremos algo del cómo usar fácilmente la tecnología para crear soluciones de accesibilidad a personas con algún tipo de discapacidad y también como crear redes wifi con materiales de bajo costo. Te llamaría la atención dejarte contagiar de la #BVS ?? Estas muy pero muy invitado.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Wilson Daniel Gordillo Ochoa (Girardot(Cund)/Espinal(Tolima))&lt;/strong&gt;. &lt;br /&gt; Ingeniero de Sistemas de profesión. Docente Investigador por pasión e Innovador Social por convicción.&lt;br /&gt; Ingeniero de Sistemas. Especialista en Docencia Universitaria y en Redes de Telecomunicaciones. Magíster en Educación.&lt;br /&gt; Actualmente Docente Investigador de la Universidad de Cundinamarca Fusagasugá. Programa Ingeniería de Sistemas.&lt;br /&gt; Docente Catedrático de la Universidad Piloto de Colombia, seccional Girardot.&lt;br /&gt; Gestor de Proyectos de Investigación y Laboratorios de Innovación Social como Red Fusa Libre, Red Espinal Libre, enREDate, cuyo propósito en común es apropiar socialmente el conocimiento en nuestras comunidades convirtiendolas activamente en parte de la solución para mejorar sus condiciones de vida.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.redfusalibre.co&quot;&gt;Red Fusa Libre&lt;/a&gt;&lt;br /&gt; Red Espinal Libre&lt;br /&gt; EnREDate&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-59&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;11:00 am - 12:00 m&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Flujo de Trabajo Orientado a Código con Drupal&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Esta charla quiere compartir la experiencia de la fábrica de software de la ACDTIC, en la construcción de sitios y portales web distritales, a partir de la estandarización, modularización, y contribución de características funcionales para el CMS Drupal, las cuales son desarrolladas en un ambiente de desarrollo colaborativo. &lt;br /&gt; Nuestro enfoque apropia Software Libre, mejores prácticas de desarrollo, metodologías ágiles y las recomendaciones de la Guía de Sitios Web v3.0, para brindar accesibilidad, usabilidad y gobierno electrónico.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Fabián Hernández / David Triana (Bogotá)&lt;/strong&gt;&lt;br /&gt; &lt;strong&gt;Fabián Hernández. &lt;/strong&gt;Soy Ingeniero Electrónico bogotano, usuario y promotor de Software Libre con experiencia en el campo de desarrollo web y administración de sistemas GNU/Linux, miembro cofundador de la comunidad Juuntos Latinoamérica y desarrollador activo de la plataforma CMS Jokte!. Actualmente creando proyectos con Drupal para las Entidades del Distrito Capital.&lt;br /&gt; &lt;strong&gt;David Triana.&lt;/strong&gt; Ingeniero de sistemas entusiasta del software libre, desarrollador frontend con experiencia de 5 años utilizando CMS. Desarrollador de la alta consejería TIC, actualmente creando proyectos con Drupal para diferentes Entidades del Distrito Capital.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Fábrica de Software de la Alta Consejería Distrial de TIC&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-60&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;12:00 md - 12:45 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;ALMUERZO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-61&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;1:00 pm - 2:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Visión Artificial con Raspberry pi&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Metodologías de visión artificial sobre dispositivo embebido Raspberry pi&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Diego Alveniz Escobar Figueroa (Fusagasugá)&lt;/strong&gt;. Estudiante de Ing. Electrónica (UDEC), Promotor de Cultura Libre, apasionado por la visión artificial y el Hardware libre. Perteneciente al Colectivo Ingenio Popular y semillero de Investigación KINESTASIS UDEC.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Ingenio Popular&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-62&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;2:00 pm - 3:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Normatividad Distrital para el uso y apropiación de Software Libre&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;El objetivo de la charla es hacer un recuento de las diferentes aplicaciones de herramientas, plataformas, metodologías y proyectos que hacen uso de la política de software libre en el Distrito Capital.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Nelson Darío Rico Pinzón (Bogotá)&lt;/strong&gt;. Ingeniero de sistemas con 30 años de experiencia docente, se ha desempeñado como director de sistemas en entidades distritales y nacionales, actualmente trabaja como profesional especializado en la secretaría técnica de la Comisión Distrital de Sistemas CDS, director de proyectos especiales y responsable de la promoción del Software Libre en la Alta Consejería Distrital de Tecnologías de la Información y las Comunicaciones TIC.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Secretaría General. Alta Consejería Distrital de TIC&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-63&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;3:00 pm - 3:30 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Cierre del FLISOL&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Comité Organizador&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.fusa.flisol.info&quot;&gt;FLISoL Fusagasugá&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-64&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;3:30 pm - 4:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;REFRIGERIOS&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt;&lt;span id=&quot;line-65&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-66&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h3 id=&quot;Plazoleta_Torvalds&quot;&gt;Plazoleta Torvalds&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;HORA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;TÍTULO DE PONENCIA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;DESCRIPCIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;PONENTE(S)&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-68&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;10:00 am - 11:00 am&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Estudio de la criptografía&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Una descripción de la historia de la criptografía y el estudio actual de la misma. El objetivo principal de la criptografía en la antigüedad era conseguir la confidencialidad de los mensajes. En la actualidad es la única forma de proteger nuestra información en la era digital. Se demostraran los sistemas de criptoanalisis para saber que tan segura esta nuestra información.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Daniel Camilo Ramirez Martinez (Chía)&lt;/strong&gt;. Estudiante de X semestre de Ingeniería de Sistemas (UdeC). Tecnología en formulación y evaluación de proyectos. Director de desarrollo Educamos Online.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Independiente&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-69&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;11:00 am - 12:00 m&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;¿Que necesito para crear un videojuego?&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;En esta charla veremos el estado de la industria de los videojuegos en Colombia, como comenzar y que necesitamos para dar los primeros pasos en esta fascinante industria.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Cristian Camilo Velasquez (Bogotá/Fusagasugá)&lt;/strong&gt;. Soy scrum master en Brainz interactive, miembro activo de la comunidad agil colombiana.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.brainz.co&quot;&gt;Brainz interactive&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-70&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;12:00 md - 12:45 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;ALMUERZO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-71&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;1:00 pm - 2:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Realidad Aumentada&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Software libre&lt;br /&gt; IDE: Eclipse&lt;br /&gt; Librería AR: NyARToolKit 4.1&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Jaime Paez (Bogotá)&lt;/strong&gt;. Ing de Sistemas. Magister en Educación de la Universidad Pedagógica Nacional. Docente Investigador de la Universidad Cooperativa de Colombia. Líder del grupo de investigación NEOTIC y líder del semillero de Investigación MULTYSO.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Universidad Cooperativa de Colombia - Semillero de investigación Multyso&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-72&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;2:00 pm - 3:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Zentyal Development Edition, solución para la pequeña y mediana empresa&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;El Objetivo principal es realizar un taller teórico-practico donde se verán: Instalación y configuración, configuración de red, configuración dominio, configuración Grupo de trabajo, configuración políticas de seguridad, casos de uso y aplicación, ventajas del uso de Zentyal.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Jaime Daniel Quintero Avalo (Bogotá)&lt;/strong&gt;. Estudiante de Ingeniería de sistemas de la Universidad Cooperativa de Colombia. Actualmente Líder activo del semillero de investigación MULTYSO.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Universidad Cooperativa de Colombia - Semillero de investigación Multyso&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h3 id=&quot;Plazoleta_Baker&quot;&gt;Plazoleta Baker&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;HORA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;TÍTULO DE PONENCIA&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;DESCRIPCIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;PONENTE(S)&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-76&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;10:00 am - 12:00 md&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Desarrollo de App Movil utilizando Firefox OS&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;Se Aprenderá como desarrollar un app Movil con el nuevo sistema operativo Firefox OS, basado en HTML5 con núcleo Linux y de código abierto.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Giovanny Andres Cifuentes (Fusagasugá)&lt;/strong&gt;. Desarrollador freelance. Entusiasta de las metodologías ágiles, emprendimiento y software libre.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.mozillacolombia.org&quot;&gt;Mozilla Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-77&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;12:00 md - 12:45 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;ALMUERZO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;-&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-78&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;1:00 pm - 2:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Experiencias con agilismo&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;En esta charla se hará una pequeña introducción a las metodologías ágiles y como han sido aplicadas en los entornos donde nos desarrollamos con un pequeño taller práctico&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;&lt;a class=&quot;nonexistent&quot; href=&quot;http://flisol.info/LocXue&quot;&gt;LocXue&lt;/a&gt; (Fusagasugá)&lt;/strong&gt;. Somos un semillero de la Universidad de Cundinamarca pertenecientes a la comunidad agilista, enfocados en metodologias agiles para el desarrollo de nuestros proyectos, en los cuales nos gusta innovar y ayudar en nuestra comunidad esperando generar espacios donde el conocimiento se comparta.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/locxue&quot;&gt;Comunidad Agilista&lt;/a&gt;&lt;br /&gt; &lt;a class=&quot;http&quot; href=&quot;http://www.agilescolombia.org&quot;&gt;Agiles Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-79&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;2:00 pm - 3:00 pm&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Webcomponents by Mozilla&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;¿Son los webcomponents realmente necesarios? Un vistazo a lo bueno, lo malo y inimaginable sobre el futuro de los webcomponents.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;Giovanny Andres Gongora Granada (Ibague)&lt;/strong&gt;. Desarrollador con 8 años de experiencia personal. Miembro de Mozilla Hispano y Mozilla Colombia. Ayuda en Firefox Marketplace (marketplace.firefox.com), i18n y es entrenador de Firefox OS Colombia. Dicta charlas de Web Abierta y Open Source.&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.mozillacolombia.org&quot;&gt;Mozilla Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;En años anteriores contamos con la fortuna de recibir el apoyo incondicional de &lt;strong&gt;grandes amigos&lt;/strong&gt; de la cultura libre: &lt;span id=&quot;line-76&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-77&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Gloria Meneces&lt;/strong&gt;, representante de Mozilla para Colombia, Mozillian y miembro de &lt;strong&gt;Mozilla Colombia&lt;/strong&gt; socializando con nosotros el mundo tras mozilla y patrocinando el evento. &lt;span id=&quot;line-78&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-79&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Edgar Daniel Cruz Zamudio&lt;/strong&gt;, realizador audiovisual del colectivo Cine Al Aire, participante, realizador y organizador de diferentes festivales, clips y talleres. &lt;span id=&quot;line-80&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-81&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Juan Sebastian Rojas&lt;/strong&gt;, Ingeniero de Sistemas de la Universidad de Cundinamarca, Certified Ethical Hacker, ponente de charlas de seguridad informática y Consultor Senior de seguridad en Entidad Bancaria. &lt;span id=&quot;line-82&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-83&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompaño &lt;strong&gt;Jessica Selene&lt;/strong&gt; desde &lt;strong&gt;Argentina&lt;/strong&gt; compartiendo diversos proyectos vínculados a tecnologías libres, entre ellos las redes libres. &lt;a class=&quot;nonexistent&quot; href=&quot;http://flisol.info/blog.altermundi.net/article/se-hace-camino-al-andar/&quot;&gt;En este link puedes ver como contó su experiencia&lt;/a&gt;. &lt;span id=&quot;line-84&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-85&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;También &lt;strong&gt;Fabian Hernandez&lt;/strong&gt; del colectivo latinoamericano &lt;strong&gt;Juuntos&lt;/strong&gt;, haciendo difusión del proyecto de CMS libre y latinoamérico Jokte!. &lt;a class=&quot;https&quot; href=&quot;https://groups.google.com/forum/#%21topic/juuntos/eSrj3PoPAYo&quot;&gt;Aqui en este link nos comparte un poco de su experiencia&lt;/a&gt; &lt;span id=&quot;line-86&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-87&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;Nos acompañaron e hicieron parte de la organización algun@s de los miembros de la comunidad hermana &lt;strong&gt;Red Espinal Libre&lt;/strong&gt; que junto a &lt;strong&gt;Red Fusa Libre&lt;/strong&gt; y Jessica permitieron importantes espacios en el evento. &lt;a class=&quot;http&quot; href=&quot;http://espinallibre.wordpress.com/2013/04/02/invitacion-flisol-fusa-20abril/&quot;&gt;En este link vemos como fue su invitación a participar&lt;/a&gt;. &lt;span id=&quot;line-88&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-89&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;L@s amig@s de &lt;strong&gt;Novenopiso TV/WEB&lt;/strong&gt; hicieron cobertura del evento en su capitulo número 12. &lt;a class=&quot;https&quot; href=&quot;https://www.youtube.com/watch?v=ff8luACoN5g&quot;&gt;Puedes ver el video en este link&lt;/a&gt;. (Con la salvedad de que Daivi era Deiby &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/smile4.png&quot; border=&quot;0&quot; alt=&quot;;)&quot; title=&quot;;)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; ). &lt;span id=&quot;line-90&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-91&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li class=&quot;gap&quot;&gt;Contamos con la participación de numerosos colectivos afines a esta iniciativa, visitantes y colaboradores, y en especial, entregados voluntarios y la acogida y apoyo de la misma comunidad. &lt;span id=&quot;line-92&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-93&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;&lt;img src=&quot;http://flisol.info/moin_static194/sol/img/icon-info.png&quot; border=&quot;0&quot; alt=&quot;{i}&quot; title=&quot;{i}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; &lt;em&gt;Puedes ver la información del FLISoL del año pasado &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2014/Colombia/Fusagasuga&quot;&gt;Aquí&lt;/a&gt;, del antepasado &lt;a class=&quot;http&quot; href=&quot;http://flisol.info/FLISOL2013/Colombia/Fusagasuga&quot;&gt;Aquí&lt;/a&gt;&lt;/em&gt; y &lt;strong&gt;¡reunir energías para este que se viene!.&lt;/strong&gt;&lt;/p&gt;&lt;/div&gt;</content>
		<category term="Destacado" />
		<category term="Uncategorised" />
	</entry>
	<entry>
		<title>¿Como participo?</title>
		<link rel="alternate" type="text/html" href="http://fusa.flisol.info/2015/index.php/participar/como-participo"/>
		<published>2014-03-14T03:20:21+00:00</published>
		<updated>2014-03-14T03:20:21+00:00</updated>
		<id>http://fusa.flisol.info/2015/index.php/participar/como-participo</id>
		<author>
			<name>Deiby Od</name>
			<email>deibyod&commat; gmail . com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h3 id=&quot;A.2BAL8-Asistir.2BAOE-s_al_evento.3F&quot;&gt;¿Asistirás al evento?&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;Por favor regístrate en el siguiente enlace: &lt;a class=&quot;https&quot; href=&quot;https://docs.google.com/forms/d/10EK0h0h2rDkRzQye3UT52owyf0XS01goypznFR8hYm8/viewform?usp=send_form&quot;&gt;Formulario de inscripción de asistentes&lt;/a&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; &lt;span id=&quot;line-86&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-87&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h3 id=&quot;A.2BAL8-Para_qu.2BAOk.3F&quot;&gt;¿Para qué?&lt;/h3&gt;
&lt;p&gt;&lt;span id=&quot;line-88&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;Tu registro nos permitirá prepararnos logísticamente para el número de asistentes y organizar las actividades y espacios; además, quienes se encuentren registrados pueden recibir algunos beneficios.&lt;/p&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;h3 id=&quot;A.2BAL8-Asistir.2BAOE-s_al_evento.3F&quot;&gt;¿Asistirás al evento?&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;p class=&quot;line862&quot;&gt;Por favor regístrate en el siguiente enlace: &lt;a class=&quot;https&quot; href=&quot;https://docs.google.com/forms/d/10EK0h0h2rDkRzQye3UT52owyf0XS01goypznFR8hYm8/viewform?usp=send_form&quot;&gt;Formulario de inscripción de asistentes&lt;/a&gt; &lt;img src=&quot;http://flisol.info/moin_static194/sol/img/checkmark.png&quot; border=&quot;0&quot; alt=&quot;(./)&quot; title=&quot;(./)&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; &lt;span id=&quot;line-86&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-87&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p class=&quot;line867&quot;&gt; &lt;/p&gt;
&lt;h3 id=&quot;A.2BAL8-Para_qu.2BAOk.3F&quot;&gt;¿Para qué?&lt;/h3&gt;
&lt;p&gt;&lt;span id=&quot;line-88&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;Tu registro nos permitirá prepararnos logísticamente para el número de asistentes y organizar las actividades y espacios; además, quienes se encuentren registrados pueden recibir algunos beneficios.&lt;/p&gt;&lt;/div&gt;</content>
		<category term="Destacado" />
		<category term="Uncategorised" />
	</entry>
	<entry>
		<title>¿Quienes lo hacen?</title>
		<link rel="alternate" type="text/html" href="http://fusa.flisol.info/2015/index.php/info/quienes-lo-hacen"/>
		<published>2014-03-14T03:21:00+00:00</published>
		<updated>2014-03-14T03:21:00+00:00</updated>
		<id>http://fusa.flisol.info/2015/index.php/info/quienes-lo-hacen</id>
		<author>
			<name>Deiby Od</name>
			<email>deibyod&commat; gmail . com</email>
		</author>
		<summary type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;p class=&quot;line862&quot; style=&quot;text-align: center;&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;&lt;img class=&quot;external_image&quot; src=&quot;http://www.tecnologiasod.com/flisol/images/logos/CULF.png&quot; border=&quot;0&quot; alt=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot; title=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot; style=&quot;width: 70%;&quot; /&gt;&lt;/a&gt; &lt;br /&gt; &lt;strong&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/strong&gt;&lt;/p&gt;
&lt;h3 id=&quot;Comit.2BAOk_Organizador&quot;&gt;Comité Organizador&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;NOMBRE&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;NICK&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;CORREO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;CELULAR&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-115&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.tecnologiasod.com&quot;&gt;Deiby Ordoñez Díaz&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;@&lt;a href=&quot;http://flisol.info/DeibyOd&quot;&gt;DeibyOd&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;mailto&quot; href=&quot;mailto:deibyod&commat; gmail . com&quot;&gt;deibyod&commat; gmail . com&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;311 259 XXXX&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/a&gt; &lt;br /&gt; &lt;a class=&quot;http&quot; href=&quot;http://www.mozillacolombia.org&quot;&gt;Mozilla Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-116&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/D1e90E&quot;&gt;Diego Escobar&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt; &lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;mailto&quot; href=&quot;mailto:diego31escobar&commat; gmail . com&quot;&gt;diego31escobar&commat; gmail . com&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;312 331 XXXX&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/a&gt;&lt;br /&gt; &lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/ingenipopular?fref=ts&quot;&gt;Colectivo Ingenio Popular&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-117&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://about.me/carlos6&quot;&gt;Carlos Alvarado&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;@Carlo_6a&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;mailto&quot; href=&quot;mailto:carlo.6a&commat; gmail . com&quot;&gt;carlo.6a&commat; gmail . com&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;314 2193 XXX&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt;&lt;span id=&quot;line-118&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-119&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;img src=&quot;http://flisol.info/moin_static194/sol/img/star_on.png&quot; border=&quot;0&quot; alt=&quot;{*}&quot; title=&quot;{*}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Participa, &lt;strong&gt;El FLISoL es de TODOS&lt;/strong&gt;.&lt;/p&gt;&lt;/div&gt;</summary>
		<content type="html">&lt;div class=&quot;feed-description&quot;&gt;&lt;p class=&quot;line862&quot; style=&quot;text-align: center;&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;&lt;img class=&quot;external_image&quot; src=&quot;http://www.tecnologiasod.com/flisol/images/logos/CULF.png&quot; border=&quot;0&quot; alt=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot; title=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot; style=&quot;width: 70%;&quot; /&gt;&lt;/a&gt; &lt;br /&gt; &lt;strong&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/strong&gt;&lt;/p&gt;
&lt;h3 id=&quot;Comit.2BAOk_Organizador&quot;&gt;Comité Organizador&lt;/h3&gt;
&lt;p&gt; &lt;/p&gt;
&lt;div&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background-color: #ffa851;&quot;&gt;
&lt;td style=&quot;text-align: center;&quot;&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;NOMBRE&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;NICK&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;CORREO&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;CELULAR&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;strong&gt;COMUNIDAD/COLECTIVO/ORGANIZACIÓN&lt;/strong&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-115&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://www.tecnologiasod.com&quot;&gt;Deiby Ordoñez Díaz&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;@&lt;a href=&quot;http://flisol.info/DeibyOd&quot;&gt;DeibyOd&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;mailto&quot; href=&quot;mailto:deibyod&commat; gmail . com&quot;&gt;deibyod&commat; gmail . com&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;311 259 XXXX&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/a&gt; &lt;br /&gt; &lt;a class=&quot;http&quot; href=&quot;http://www.mozillacolombia.org&quot;&gt;Mozilla Colombia&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-116&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/D1e90E&quot;&gt;Diego Escobar&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt; &lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;mailto&quot; href=&quot;mailto:diego31escobar&commat; gmail . com&quot;&gt;diego31escobar&commat; gmail . com&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;312 331 XXXX&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/a&gt;&lt;br /&gt; &lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/ingenipopular?fref=ts&quot;&gt;Colectivo Ingenio Popular&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background-color: #ffb962;&quot;&gt;&lt;span id=&quot;line-117&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;http&quot; href=&quot;http://about.me/carlos6&quot;&gt;Carlos Alvarado&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;@Carlo_6a&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;mailto&quot; href=&quot;mailto:carlo.6a&commat; gmail . com&quot;&gt;carlo.6a&commat; gmail . com&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;314 2193 XXX&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;
&lt;p class=&quot;line862&quot;&gt;&lt;a class=&quot;https&quot; href=&quot;https://www.facebook.com/groups/comunidadlinuxfusa/&quot;&gt;Comunidad de Cultura Libre de Fusagasugá - CULF&lt;/a&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt;&lt;span id=&quot;line-118&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;span id=&quot;line-119&quot; class=&quot;anchor&quot;&gt;&lt;/span&gt;&lt;img src=&quot;http://flisol.info/moin_static194/sol/img/star_on.png&quot; border=&quot;0&quot; alt=&quot;{*}&quot; title=&quot;{*}&quot; width=&quot;16&quot; height=&quot;16&quot; /&gt; Participa, &lt;strong&gt;El FLISoL es de TODOS&lt;/strong&gt;.&lt;/p&gt;&lt;/div&gt;</content>
		<category term="Destacado" />
		<category term="Uncategorised" />
	</entry>
</feed>
